apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: monitoring
  name: blackbox-exporter
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      serviceAccountName: blackbox-exporter
      containers:
      - name: blackbox-exporter
        image: quay.io/coreos/blackbox-exporter:v0.8.1
        args: [--config.file=/etc/config/blackbox.yaml]
        ports:
        - name: metrics
          containerPort: 9115
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: blackbox-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  labels:
    app: blackbox-exporter
    k8s-app: blackbox-exporter
  name: blackbox-exporter
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app: blackbox-exporter
