apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-exporter
  labels:
    k8s-app: blackbox-exporter
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: blackbox-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: http-metrics
    interval: 30s
    honorLabels: true
