apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  labels:
    prometheus: k8s
spec:
  replicas: 2
  version: v1.7.1
  externalUrl: http://127.0.0.1:8001/api/v1/proxy/namespaces/monitoring/services/prometheus-k8s:web/
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  resources:
    requests:
      memory: 2Gi
  storage:
    volumeClaimTemplate:
      metadata:
        name: prometheus
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: platinum
        resources:
          requests:
            storage: 1Ti
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
      port: web
