global:
  resolve_timeout: 5m
  smtp_from: admin@{{domain}}
  smtp_smarthost: {{smtpHost}}
  smtp_auth_username: {{smtpUsername}}
  smtp_auth_password: {{smtpPassword}}
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'team-X-mails'
  routes:
  - match:
      alertname: DeadMansSwitch
    receiver: 'null'
receivers:
- name: 'team-X-mails'
  email_configs:
  - to: '{{alertsEmailRecipient}}'
- name: 'null'
